language: minimal
services:
- docker
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
env:
  global:
  - secure: xnQmEwd0x/ARdqgk2nvQsrHVarQp18gq8s+a7w2AEfW8XrZgYumLES8QKKKQNPMjhSS887iaGO4uc3ZIsuA5wLiNAIz97GNKgQ7ksCEA47y3/fGBpUaJBVlnck51lrHCJ/qnHL2NIClRgziVEO5c1sEcBEua1BBGq7xBu1wFNpQ8A/OZkzd76/tGMiMJTK66SE5TiLpPRiEghUzsPIdzXSYniiyzF2PSehKbsI/10urAfRSsaPjiwPSu6f845zZLdomfuvvEJiX/gGUaZzueRXHChPvx0jOJsKMg1D8BxRaPR2gRVlhAt+ByRcjtqUFEs4Uqao4Rsn3Qsc9tlA3g3Rb6w9xd0b3xCRvGcfnGObwpIFgZII3sZ5Yzive0Xa/SOp+Ut3DDhb90uq5L0ClQ9WMQKW9Np/yzWxRNNAUmK57F3MEg5n7GaYhiCUjqgRL0zeXw7p0z4S24CxHazGoA6qmZW5oJQBJxXda2R7cvWEuqHj6mL8ri6V5oSodYEwSamvndCv1BOrVrYPpUj8fPjT477PlciWjtJW7IBEqFcCWDoyjH+UOXLKjztyuntiPhZ1lHXEJb0ZrpjLuqvmIBcWWD2XhH1kYgosJ2qaDxr+1uD0X/s2VJJOzIHPKk6y9kxSBQkyY9+lzXZS6W34HI/fwuRs3JVXh0JKd4ACXb8GA=
  - secure: nVhsYCT6HhJArWce98sMoR8T4ZvurYDixRPS5CUWQQRRF05GU/BAXkMN4ynL56P/775Kon6hluM+XBU7A1GMpClrf9Edq3NXJX3+Pufzp8jDt1VSyOYTBqkTWB8M6sJm1GAxE704cBVseabK6Z2FWWDcxSzyS7T4WycRQbz9xizi3pGLVmGtgF6P8u+AOb/NL4e8itfqzGYI5EpwKA55yAAcIuAZ67cu/+p1T6ErRJgrGT17QQSAPgoRhWONQNNq63BILgZpAWbfdKZI24NO61hXpFm5tWpqWoNbCzPJUaeaSbAS5V1jCYJOM1mb4iXVDA8yzyWU73mWMCNn5TpdJY5Aly4992MLQ8aKLvCGxD/GoNnQ/VGOWzdaT5tcKEZS+6P7whC0qce3qHPVxPcDpO7cHckWF2XksWgWDiuULKTAIzGM6BSw4jodGDRPEaxxe14WaNI+H6MaMGjlVACI6DFfJOq6f02C4m6a8R+8nQX1SbpIUMhsCWbLq+6EOpPDcgx7mp9T054/kj3ENZTfGJCKmJtZTnf0UtnqvuYiLq192uufupdzkHNDj6JnmCOCoNgLJD1gfwpz8MOhiULUJu3nTK6vAPsyixDPdYAAAvpqg4PRywZgZv254pC/nMmnAu8Z9qKQ7nLmZXSNpwEqfWkxhra5qxDDB7n5dwcI5ik=
